#include <stdio.h>
#include <string.h>
/*
    运行a.out后不产生core文件
    解决方法：
    1.ulimit -c unlimited
    2.运行cat /proc/sys/kernel/core_pattern查看相关设置
    若是下面的设置则代表core文件被当成bug文件拿去检查了
    |/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E
    文件的结果会被Linux的一个进程apport 吞掉，拿去检查是不是系统的bug，所以看不到core文件了。
    只需要关闭进程apport即可
    运行：sudo service apport stop
    
    以后遇到段错误(核心已转储)时需调试程序时，可以将core的core file size大小从0->ulimited
    然后使用gcc xxx.c -o xxx -g 编译程序
    再进入gdb模式使用命令：core-file core来查看段错误的信息
    例如以下操作：
    (gdb) core-file core
    [New LWP 5440]
    Core was generated by `./a.out'.
    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  0x000055dbcbca1602 in main () at core.c:6
    6	    strcpy(buf,"hello");    //段错误 (核心已转储)


*/
int main(void) {
    char * buf;     //野指针
    strcpy(buf,"hello");    //段错误 (核心已转储)
    return 0;
}
